@startuml usecase
left to right direction
actor User as U

package useCase {
    usecase "Visualiser liste produits" as UC1
    usecase "Consulter un produit" as UC2
    usecase "Ajouter modifier supprimer au panier" as UC3
    usecase "Commander des produits" as UC4
}

U --> UC1
UC1 <.. UC2 
UC2 <.. UC3 
UC3 <-- UC4 
@enduml