left to right direction

entity "Produit" as produit {
    * id
    --
    * nom
    * description
    * prix
    * image
    * categorie
}

entity "ProduitCommande" as panier {
    * id
    --
    * id_produit
    * id_commande
    * quantite
}

entity "Commande" as commande {
    * id
    --
    * id_user
    * prix_total
    * date
}

entity "Utilisateur" as user {
    * id
    --
    * nom
    * prenom
    * adresse
    * telephone
}

produit ||--o{ panier
panier }|--|| commande
user ||--|{ commande
