@startuml sequence
actor "Client" as User
participant "listes produits" as L
participant "un produit" as P
participant "ajout au panier" as O

User -> L : clic ajout au panier sur cards
activate O
L -> O : ajout au panier sur card
O -> User : message ok
deactivate 

User -> P : clic ajout au panier sur card
P -> O : ajout au panier sur card
O -> User : message ok


@enduml